#!/usr/bin/env python3
"""
wav_to_mif.py -- convert any WAV file into the song.mif consumed by
wav_rom.vhd. The output is 16-bit signed mono at WAV_SAMPLE_RATE_HZ.

Usage:
    python3 wav_to_mif.py input.wav [song.mif]

Notes:
  - Produces exactly DEPTH words (pads with silence). DEPTH must match
    `wav_rom.vhd` and the capacity of the loader target range.
  - If the source is stereo, both channels are averaged.
  - Update WAV_SAMPLE_COUNT in audio_pkg.vhd to the reported sample count
    (or to DEPTH if you want the loader to write the full ROM extent).

Dependencies: standard library only (wave, audioop).
"""

import sys
import wave
import audioop
import struct
import os

# Must match audio_pkg.vhd / wav_rom.vhd
TARGET_SR  = 8000
DEPTH      = 131072            # 2^17, matches wav_rom
DEFAULT_OUT = "song.mif"

def load_wav_as_mono_s16(path, target_sr):
    with wave.open(path, "rb") as w:
        nch     = w.getnchannels()
        sampw   = w.getsampwidth()
        fr      = w.getframerate()
        nframes = w.getnframes()
        raw     = w.readframes(nframes)

    # Normalize to 16-bit signed PCM
    if sampw == 1:
        raw = audioop.bias(raw, 1, -128)
        raw = audioop.lin2lin(raw, 1, 2)
        sampw = 2
    elif sampw == 3:
        raw = audioop.lin2lin(raw, 3, 2)
        sampw = 2
    elif sampw == 4:
        raw = audioop.lin2lin(raw, 4, 2)
        sampw = 2

    # Collapse to mono
    if nch == 2:
        raw = audioop.tomono(raw, sampw, 0.5, 0.5)
        nch = 1

    # Resample
    if fr != target_sr:
        raw, _ = audioop.ratecv(raw, sampw, nch, fr, target_sr, None)

    # Unpack to list of int16
    n = len(raw) // 2
    return list(struct.unpack("<" + "h"*n, raw))

def write_mif(samples, path, depth):
    n = min(len(samples), depth)
    with open(path, "w") as f:
        f.write("-- auto-generated by wav_to_mif.py -- do not edit\n")
        f.write("WIDTH=16;\n")
        f.write("DEPTH={};\n".format(depth))
        f.write("ADDRESS_RADIX=UNS;\n")
        f.write("DATA_RADIX=HEX;\n")
        f.write("CONTENT BEGIN\n")
        # Write non-zero samples
        for i in range(n):
            v = samples[i] & 0xFFFF
            f.write("    {:d} : {:04X};\n".format(i, v))
        # Pad remainder with zeros in one range
        if n < depth:
            f.write("    [{}..{}] : 0000;\n".format(n, depth-1))
        f.write("END;\n")
    return n

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) >= 3 else DEFAULT_OUT

    samples = load_wav_as_mono_s16(in_path, TARGET_SR)
    written = write_mif(samples, out_path, DEPTH)

    dur = written / TARGET_SR
    print("Wrote {} ({} samples, {:.2f} s, {} Hz mono s16)".format(
        out_path, written, dur, TARGET_SR))
    print("Set WAV_SAMPLE_COUNT = {} in audio_pkg.vhd".format(written))

if __name__ == "__main__":
    main()
